### ISSUE TITLE
Corrupted Library [install with both github and PyPI packge method]

### ISSUE THREAD

**Issue by Amin-Tgz** [tsyet12/Moptimal#3]
after installation, when import solvers get this error:

```
from EvoOpt import solvers
Traceback (most recent call last):

  File "<ipython-input-7-18bb446d7216>", line 1, in <module>
    from EvoOpt import solvers

  File "D:\WorkingPartition\University\MS\Thesis3\Optimization\EvoOpt-master\EvoOpt\solvers\__init__.py", line 1, in <module>
    import DuelistAlgorithm

ModuleNotFoundError: No module named 'DuelistAlgorithm'
```

**Comment by tsyet12** [comment]
Hi. I think your package installed perfectly. You just used the wrong import code.
Use "from EvoOpt.solvers.DuelistAlgorithm import DuelistAlgorithm as DA"

Example:
```python
#import solver by using {library name}.solvers.{solver name} import {solver name}
from EvoOpt.solvers.DuelistAlgorithm import DuelistAlgorithm as DA

#suppose you have a model with input of x,y. You want to minimize 3x+y^2.
def model(x,y):
  return 3*x+y*y

var_name=["x","y"] #names for variable
lb=[0,10] #your lower boundaries
ub=[-5,5] #your upper boundaries

solver=DA(model,var_name,lb,ub,pop=20,max_gen=10000) #setup your solver
solver.solve() #actually run the solver
```

You can also see the examples in readme file. There is also an example for a reactor in the example folder.
